modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/squoshi/cnd-revamp"

[[mods]]
modId="missinginaction"
version="${file.jarVersion}"
displayName="Missing in Action"
#logoFile="mia.png"
credits="Jackiecrazy, the original author of Cloak and Dagger which this mod is based on."
authors="squoshi, Jackiecrazy"
description='''
Simple stealth and backstab implementation for Minecraft mod and modpack developers. Based on the original Cloak and Dagger mod by Jackiecrazy.
'''

[[dependencies.missinginaction]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.missinginaction]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"